services:
  wanderin:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/wanderin:cached
    environment:
      - PYTHONPATH=/workspaces/wanderin