name: WebSeekly Nodes Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: [
      'src/langgraph/nodes/**', 
      'test/**',
      '.github/workflows/pytest.yml'
      ]

defaults:
  run:
    shell: bash

jobs:
  test-crawl-node:
    name: Test of CrawlNode
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

      - name: Verify uv installation
        run: uv --version

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Print PYTHONPATH
        run: echo "PYTHONPATH=${{ env.PYTHONPATH }}"

      - name: Run pytest
        run: uv run pytest -s test/test_crawl_node.py

      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip

  test-keyword-node:
    name: Test of KeywordNode
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

      - name: Verify uv installation
        run: uv --version

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Print PYTHONPATH
        run: echo "PYTHONPATH=${{ env.PYTHONPATH }}"

      - name: Run pytest for KeywordNode
        run: uv run pytest -s test/test_keyword_node.py

      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip

  test-search-node:
    name: Test of SearchNode
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

      - name: Verify uv installation
        run: uv --version

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Print PYTHONPATH
        run: echo "PYTHONPATH=${{ env.PYTHONPATH }}"

      - name: Run pytest for SearchNode
        run: uv run pytest -s test/test_search_node.py

      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip

  test-scrape-node:
    name: Test of ScrapeNode
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

      - name: Verify uv installation
        run: uv --version

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Print PYTHONPATH
        run: echo "PYTHONPATH=${{ env.PYTHONPATH }}"

      - name: Run pytest for ScrapeNode
        run: uv run pytest -s test/test_scrape_node.py

      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip